added alternative Rappture:result function to tcl bindings added Rappture::Units::convert function. adjusted makefile for more files to compile adjusted configure file to once again check for bltInt.h adjusted children function to allow for blank path

diff --git a/trunk/src/tcl/configure b/trunk/src/tcl/configure
--- a/trunk/src/tcl/configure
+++ b/trunk/src/tcl/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="src/RpLibraryTclInterface.cc"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE RANLIB ac_ct_RANLIB build build_cpu build_vendor build_os host host_cpu host_vendor host_os CYGPATH TCL_INCLUDES TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIBS TCL_DEFS TCL_SHLIB_LD_LIBS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_STUB_LIB_FILE TCL_LIB_SPEC TCL_BUILD_LIB_SPEC TCL_STUB_LIB_SPEC TCL_BUILD_STUB_LIB_SPEC CLEANFILES CC CFLAGS ac_ct_CC CFLAGS_DEBUG CFLAGS_OPTIMIZE STLIB_LD SHLIB_LD SHLIB_CFLAGS SHLIB_LDFLAGS TCL_DBGX CFLAGS_DEFAULT LDFLAGS_DEFAULT MAKE_LIB MAKE_SHARED_LIB MAKE_STATIC_LIB Rappture_LIB_FILE SHLIB_LD_LIBS TCLSH_PROG PACKAGE VERSION PATCHLEVEL EXACT_VERSION NODOT_VERSION LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE RANLIB ac_ct_RANLIB build build_cpu build_vendor build_os host host_cpu host_vendor host_os CYGPATH TCL_INCLUDES TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIBS TCL_DEFS TCL_SHLIB_LD_LIBS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_STUB_LIB_FILE TCL_LIB_SPEC TCL_BUILD_LIB_SPEC TCL_STUB_LIB_SPEC TCL_BUILD_STUB_LIB_SPEC BLT_SRC_DIR CLEANFILES CC CFLAGS ac_ct_CC CFLAGS_DEBUG CFLAGS_OPTIMIZE STLIB_LD SHLIB_LD SHLIB_CFLAGS SHLIB_LDFLAGS TCL_DBGX CFLAGS_DEFAULT LDFLAGS_DEFAULT MAKE_LIB MAKE_SHARED_LIB MAKE_STATIC_LIB Rappture_LIB_FILE SHLIB_LD_LIBS TCLSH_PROG PACKAGE VERSION PATCHLEVEL EXACT_VERSION NODOT_VERSION LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -2390,64 +2390,66 @@ echo "${ECHO_T}file not found" >&6
 # Look for bltInt.h on the normal include path.  If not found, look
 # for it in the --with-blt directory.
 #--------------------------------------------------------------------
-#AC_MSG_CHECKING([for bltInt.h])
-#BLT_SRC_DIR=""
-#if test "x$blt_source_dir" != "x" ; then
-#  #
-#  # Verify that a tclConfig.sh file exists in the directory specified
-#  # by --with-blt.
-#  #
-#  if test -r "$blt_source_dir/bltInt.h" ; then
-#    BLT_SRC_DIR="$blt_source_dir"
-#  elif test -r "$blt_source_dir/src/bltInt.h" ; then
-#    BLT_SRC_DIR="$blt_source_dir/src"
-#  fi
-#else
-#  #
-#  # Otherwise, search for the bltInt.h include file...
-#  # 1. Search previously named locations.
-#  #
-#  for dir in \
-#   $prefix \
-#   $exec_prefix
-#  do
-#    if test -r "$dir/bltInt.h" ; then
-#      BLT_SRC_DIR="$dir"
-#      break
-#    elif test -r "$dir/include/bltInt.h" ; then
-#      BLT_SRC_DIR="$dir/lib"
-#      break
-#    fi
-#  done
-#  #
-#  #  2. Search source directories.
-#  #
-#  if test "x$BLT_SRC_DIR" = "x" ; then
-#    for dir in \
-#     `ls -dr ../blt[[2-3]].[[0-9]]* 2>/dev/null` \
-#     ../blt \
-#     `ls -dr ../../blt[[2-3]].[[0-9]]* 2>/dev/null` \
-#     ../../blt \
-#     `ls -dr ../../../blt[[2-3]].[[0-9]]* 2>/dev/null` \
-#     ../../../blt
-#    do
-#      if test -r "$dir/bltInt.h" ; then
-#	tclConfigFile="$dir/bltInt.h"
-#	break
-#      fi
-#    done
-#  fi
-#fi
-#
-#AC_MSG_RESULT([${BLT_SRC_DIR}])
-#
-#if test "x$BLT_SRC_DIR" = "x" ; then
-#  echo "can't find BLT include file \"bltInt.h\""
-#  echo "use --with-blt=DIR to specify the location of the BLT sources"
-#  exit 1
-#fi
-#
-#AC_SUBST(BLT_SRC_DIR)
+echo "$as_me:$LINENO: checking for bltInt.h" >&5
+echo $ECHO_N "checking for bltInt.h... $ECHO_C" >&6
+BLT_SRC_DIR=""
+if test "x$blt_source_dir" != "x" ; then
+  #
+  # Verify that a tclConfig.sh file exists in the directory specified
+  # by --with-blt.
+  #
+  if test -r "$blt_source_dir/bltInt.h" ; then
+    BLT_SRC_DIR="$blt_source_dir"
+  elif test -r "$blt_source_dir/src/bltInt.h" ; then
+    BLT_SRC_DIR="$blt_source_dir/src"
+  fi
+else
+  #
+  # Otherwise, search for the bltInt.h include file...
+  # 1. Search previously named locations.
+  #
+  for dir in \
+   $prefix \
+   $exec_prefix
+  do
+    if test -r "$dir/bltInt.h" ; then
+      BLT_SRC_DIR="$dir"
+      break
+    elif test -r "$dir/include/bltInt.h" ; then
+      BLT_SRC_DIR="$dir/lib"
+      break
+    fi
+  done
+  #
+  #  2. Search source directories.
+  #
+  if test "x$BLT_SRC_DIR" = "x" ; then
+    for dir in \
+     `ls -dr ../blt[2-3].[0-9]* 2>/dev/null` \
+     ../blt \
+     `ls -dr ../../blt[2-3].[0-9]* 2>/dev/null` \
+     ../../blt \
+     `ls -dr ../../../blt[2-3].[0-9]* 2>/dev/null` \
+     ../../../blt
+    do
+      if test -r "$dir/bltInt.h" ; then
+	tclConfigFile="$dir/bltInt.h"
+	break
+      fi
+    done
+  fi
+fi
+
+echo "$as_me:$LINENO: result: ${BLT_SRC_DIR}" >&5
+echo "${ECHO_T}${BLT_SRC_DIR}" >&6
+
+if test "x$BLT_SRC_DIR" = "x" ; then
+  echo "can't find BLT include file \"bltInt.h\""
+  echo "use --with-blt=DIR to specify the location of the BLT sources"
+  exit 1
+fi
+
+
 
 #--------------------------------------------------------------------
 # __CHANGE__
@@ -4264,6 +4266,7 @@ s,@TCL_LIB_SPEC@,$TCL_LIB_SPEC,;t t
 s,@TCL_BUILD_LIB_SPEC@,$TCL_BUILD_LIB_SPEC,;t t
 s,@TCL_STUB_LIB_SPEC@,$TCL_STUB_LIB_SPEC,;t t
 s,@TCL_BUILD_STUB_LIB_SPEC@,$TCL_BUILD_STUB_LIB_SPEC,;t t
+s,@BLT_SRC_DIR@,$BLT_SRC_DIR,;t t
 s,@CLEANFILES@,$CLEANFILES,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
