after the core rappture library (librappture.so) is created the include files necessary to compile all other bindings are copied to the top level include directory. python, perl, matlab, octave and tcl bindings now refer to this top level include directory to find header files.
fortran and c examples are only compiled if we find a compiler, this check
helps prevent builds from failing before the libraries are installed.

added more checks to the configure script

removed rappture search paths from perl's unix build because perl could find
an older version of rappture and compile against it. I would rather the build
fail and have the person enter a valid prefix.

addrd the -fPIC flag to CFLAGS in src2's makefile

diff --git a/trunk/configure.in b/trunk/configure.in
--- a/trunk/configure.in
+++ b/trunk/configure.in
@@ -1,6 +1,7 @@
 AC_INIT(rappture, 1.1, rappture@nanohub.org)
 
 VERSION=0.0.1
+AC_SUBST(VERSION)
 
 #------------------------------------------------------------------------
 # Handle the --prefix=... option
@@ -18,6 +19,8 @@ if test "${libdir}" != "${prefix}/lib"; then
 else
     LIB_SEARCH_DIRS="-L ${libdir}"
 fi
+
+AC_SUBST(LIB_SEARCH_DIRS)
 
 AC_PROG_INSTALL
 AC_PROG_MAKE_SET
@@ -38,66 +41,140 @@ AC_CHECK_HEADERS(string,,AC_MSG_WARN(STL classes missing ?))
 AC_CHECK_HEADERS(list,,AC_MSG_WARN(STL classes missing ?))
 AC_CHECK_HEADERS(vector,,AC_MSG_WARN(STL classes missing ?))
 
-AC_PROG_F77([f77 fort77 g77 f90 xlf xlf90 fl32])
+AC_PROG_F77([g77 f77 fort77 f90 xlf xlf90 fl32])
 
-AC_ARG_WITH(matlab, [  --with-matlab[=DIR]         Build Matlab bindings if MEX compiler is found])
-AC_ARG_WITH(matlab_arch, [  --with-matlab-arch[=ARCH]         Build Matlab bindings for ARCH architecture])
-AC_ARG_WITH(mexext, [  --with-mexext[=ARCH]         Suggest an extension for building mex files])
-dnl AC_CHECK_PROG(MEX, mex, mex, false)
+
+
+
+dnl AC_ARG_ENABLE(
+dnl     [tcl],
+dnl     [AS_HELP_STRING([--enable-tcl], [build tcl bindings @<:@default=check@:>@])],
+dnl     [],
+dnl     [enable_tcl=check])
+dnl
+dnl BUILD_TCL=yes
+dnl AC_SUBST(BUILD_TCL)
+
+
+dnl AC_ARG_ENABLE (
+dnl     [matlab],
+dnl     [AS_HELP_STRING([--enable-matlab], [build matlab bindings @<:@default=check@:>@])],
+dnl     [],
+dnl     [enable_matlab=check])
+dnl BUILD_MATLAB=yes
+dnl AC_SUBST(BUILD_MATLAB)
+
+AC_ARG_WITH(
+    [matlab],
+    [AS_HELP_STRING([--with-matlab[=DIR]],
+        [location of matlab and mex compiler @<:@default=check@:>@])],
+    [],
+    [with_matlab=check])
+
+AC_ARG_WITH(
+    [matlab_arch],
+    [AS_HELP_STRING([--with-matlab-arch[=ARCH]],
+        [build Matlab bindings for ARCH architecture @<:@default=check@:>@])],
+    [],
+    [with_matlab_arch=check])
+
+AC_ARG_WITH(
+    [mexext],
+    [AS_HELP_STRING([--with-mexext[=ARCH]],
+        [fallback extension for building mex files @<:@default=check@:>@])],
+    [],
+    [with_mexext=check])
+
 MEX=
 MEX_ARCH=
 MEXEXT=
-if test "$with_matlab" != "no" ; then
-    dnl WITH_MATLAB = "yes"
-    if test -x "$with_matlab/bin/mex"
-    then
-        echo Found mex in $with_matlab/bin/mex
-        MEX="$with_matlab/bin/mex"
-    else
-        if test -x "$with_matlab"
+dnl if test "$enable_matlab" != "no" ; then
+    AC_MSG_CHECKING([for mex])
+    if test "$with_matlab" != "no" ; then
+        dnl WITH_MATLAB = "yes"
+        if test -x "$with_matlab/bin/mex"
         then
-            echo Found mex in $with_matlab
-            MEX="$with_matlab"
+            echo Found mex in $with_matlab/bin/mex
+            MEX="$with_matlab/bin/mex"
         else
-            AC_PATH_PROG(MEX, mex)
-        fi
-    fi
-    if test "x$MEX" != "x" ; then 
-        mexext_fxn=`dirname $MEX`/mexext
-        if test "x$mexext_fxn" != "x"; then
-            MEXEXT=`$mexext_fxn`
-            if test "x${MEXEXT}" = "x" ; then
-                MEXEXT="mexglx"
+            if test -x "$with_matlab"
+            then
+                echo Found mex in $with_matlab
+                MEX="$with_matlab"
+            else
+                AC_PATH_PROG(MEX, mex)
             fi
-            echo Using extension $MEXEXT
         fi
-    fi
-fi
-if test "x$with_matlab_arch" != "x" ; then
-    MEX_ARCH="-arch=$with_matlab_arch"
-fi
-
-dnl AM_CONDITIONAL(WITH_MATLAB, test x$MEX != x)
-
-AC_ARG_WITH(octave, [  --with-octave[=DIR]         Build Octave bindings if MKOCTFILE compiler is found])
-dnl AC_CHECK_PROG(MKOCTFILE, mkoctfile, mkoctfile, false)
-MKOCTFILE=
-if test "$with_octave" != "no" ; then
-    if test -x "$with_octave/bin/mkoctfile"
-    then
-        echo Found octave in $with_octave/bin/mkoctfile
-        MKOCTFILE="$with_octave/bin/mkoctfile"
-    else
-        if test -x "$with_octave"
-        then
-            echo Found mkoctfile in $with_octave
-            MKOCTFILE="$with_octave"
+        AC_MSG_RESULT([${MEX}])
+        if test "x$with_matlab_arch" != "x" ; then
+            echo "using matlab architecture \"$with_matlab_arch\""
+            MEX_ARCH="-arch=$with_matlab_arch"
+        dnl else
+            dnl # if $with_matlab_arch is blank, get the os name from uname
+        fi
+        if test "x$MEX" != "x" ; then 
+            mexext_fxn=`dirname $MEX`/mexext
+            if test "x$mexext_fxn" != "x"; then
+                MEXEXT=`$mexext_fxn`
+                if test "x${MEXEXT}" = "x" ; then
+                    dnl # we should be doing an os type check instead of default mexglx
+                    dnl # use $with_matlab_arch
+                    if test "$with_mexext" != "check" ; then
+                        MEXEXT="mexglx"
+                    fi
+                fi
+                echo "Using mex file extension \"$MEXEXT\""
+                AC_MSG_RESULT([${MEXEXT}])
+            fi
         else
-            AC_PATH_PROG(MKOCTFILE, mkoctfile)
+            echo "can't find the matlab compiler \"mex\""
+            echo "use --with-matlab=DIR to specify the location of a matlab installation"
+            exit 1
         fi
     fi
-fi
-dnl AM_CONDITIONAL(WITH_OCTAVE, test x$MKOCTFILE != x)
+dnl fi
+AC_SUBST(MEX)
+AC_SUBST(MEX_ARCH)
+AC_SUBST(MEXEXT)
+
+
+dnl AC_ARG_ENABLE(
+dnl     [octave],
+dnl     [AS_HELP_STRING([--enable-octave], [build octave bindings @<:@default=check@:>@])],
+dnl     [],
+dnl     [enable_octave=check])
+dnl BUILD_OCTAVE=yes
+dnl AC_SUBST(BUILD_OCTAVE)
+
+
+AC_ARG_WITH(
+    [octave],
+    [AS_HELP_STRING([--with-octave[=DIR]],
+        [location of octave compiler MKOCTFILE @<:@default=check@:>@])],
+    [],
+    [with_octave=check])
+
+MKOCTFILE=
+dnl if test "$enable_octave" != "no" ; then
+    AC_MSG_CHECKING([for mkoctfile])
+    if test "$with_octave" != "no" ; then
+        if test -x "$with_octave/bin/mkoctfile"
+        then
+            echo Found octave in $with_octave/bin/mkoctfile
+            MKOCTFILE="$with_octave/bin/mkoctfile"
+        else
+            if test -x "$with_octave"
+            then
+                echo Found mkoctfile in $with_octave
+                MKOCTFILE="$with_octave"
+            else
+                AC_PATH_PROG(MKOCTFILE, mkoctfile)
+            fi
+        fi
+    fi
+    AC_MSG_RESULT([${MKOCTFILE}])
+dnl fi
+AC_SUBST(MKOCTFILE)
 
 
 dnl perl and python check borrowed from 
@@ -106,12 +183,25 @@ dnl
 dnl Perl is just needed for generating some data for XSLtmark
 dnl
 
-AC_ARG_WITH(perl, [  --with-perl[=DIR]         Build Perl bindings if found])
-dnl AC_CHECK_PROG(PERL, perl, perl, false)
-dnl AM_CONDITIONAL(WITH_PERL, test "$PERL" != "false")
+dnl AC_ARG_ENABLE(
+dnl     [perl],
+dnl     [AS_HELP_STRING([--enable-perl], [build perl bindings @<:@default=check@:>@])],
+dnl     [],
+dnl     [enable_perl=check])
+
+dnl BUILD_PERL=yes
+dnl AC_SUBST(BUILD_PERL)
+
+AC_ARG_WITH(
+    [perl],
+    [AS_HELP_STRING([--with-perl[=DIR]], [location of perl @<:@default=check@:>@])],
+    [],
+    [with_perl=check])
+
 PERL=
 PERL_INCLUDES=
 PERL_SITE_PACKAGES=
+AC_MSG_CHECKING([for mkoctfile])
 if test "$with_perl" != "no" ; then
     if test -x "$with_perl/bin/perl"
     then
@@ -128,18 +218,35 @@ if test "$with_perl" != "no" ; then
     fi
     PERL_SITE_PACKAGES='$(libdir)/perl5'
 fi
-dnl AM_CONDITIONAL(WITH_PERL, test x$PERL != x)
+AC_MSG_RESULT([${PERL}])
+AC_SUBST(PERL)
+AC_SUBST(PERL_INCLUDES)
+AC_SUBST(PERL_SITE_PACKAGES)
 
 dnl
 dnl check for python
 dnl
+
+dnl AC_ARG_ENABLE(
+dnl     [python],
+dnl     [AS_HELP_STRING([--enable-pyton], [build python bindings @<:@default=check@:>@])],
+dnl     [],
+dnl     [enable_python=check])
+dnl 
+dnl BUILD_PYTHON=yes
+dnl AC_SUBST(BUILD_PYTHON)
 
 PYTHON=
 PYTHON_VERSION=
 PYTHON_INCLUDES=
 PYTHON_SITE_PACKAGES=
 pythondir=
-AC_ARG_WITH(python, [  --with-python[=DIR]       Build Python bindings if found])
+AC_ARG_WITH(
+    [python],
+    [AS_HELP_STRING([--with-python[=DIR]],[location of python @<:@default=check@:>@])],
+    [],
+    [with_python=check])
+
 if test "$with_python" != "no" ; then
     if test -x "$with_python/bin/python"
     then
@@ -193,25 +300,15 @@ if test "$with_python" != "no" ; then
         pythondir='$(libdir)/python${PYTHON_VERSION}/site-packages'
     fi
 fi
-dnl AM_CONDITIONAL(WITH_PYTHON, test x$PYTHON != x)
 
 AC_SUBST(pythondir)
 dnl AC_SUBST(PYTHON_SUBDIR)
 
-AC_SUBST(MEX)
-AC_SUBST(MEX_ARCH)
-AC_SUBST(MEXEXT)
-AC_SUBST(MKOCTFILE)
-AC_SUBST(PERL)
-AC_SUBST(PERL_INCLUDES)
-AC_SUBST(PERL_SITE_PACKAGES)
 AC_SUBST(PYTHON)
 AC_SUBST(PYTHON_VERSION)
 AC_SUBST(PYTHON_INCLUDES)
 AC_SUBST(PYTHON_SITE_PACKAGES)
-AC_SUBST(LIB_SEARCH_DIRS)
 
-AC_SUBST(VERSION)
 
 RP_BASE=`pwd`
 AC_SUBST(RP_BASE)
