moved encode code to src2/core so it can be used in librappture2 for nanovis updated nanovis configure script updated src and src2/core makefiles with encode code move

diff --git a/vizservers/configure b/vizservers/configure
--- a/vizservers/configure
+++ b/vizservers/configure
@@ -3678,34 +3678,43 @@ RP_DIR=""
 echo "$as_me:$LINENO: checking for rappture" >&5
 echo $ECHO_N "checking for rappture... $ECHO_C" >&6
 if test "x$with_rappture" != "x" ; then
-    if test -f "$with_rappture"
-    then
-        echo "$as_me:$LINENO: result: no" >&5
+    if test "x$with_rappture" != "xprefix" ; then
+        if test -f "$with_rappture"
+        then
+            echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-        { { echo "$as_me:$LINENO: error: please provide --with-rappture with directory" >&5
+            { { echo "$as_me:$LINENO: error: please provide --with-rappture with directory" >&5
 echo "$as_me: error: please provide --with-rappture with directory" >&2;}
    { (exit 1); exit 1; }; }
-    else
-        if test -d "$with_rappture"
-        then
-            if test -r "$with_rappture/include/rappture2/rappture2.h" -a -r "$with_rappture/lib/librappture2.a"
+        else
+            if test -d "$with_rappture"
             then
-                RP2_INCL_DIR="$with_rappture/include/rappture2"
-                RP_DIR="$with_rappture"
+                if test -r "$with_rappture/include/rappture2/rappture2.h" -a -r "$with_rappture/lib/librappture2.a"
+                then
+                    RP2_INCL_DIR="$with_rappture/include/rappture2"
+                    RP_DIR="$with_rappture"
+                    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+                else
+                    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+                    { { echo "$as_me:$LINENO: error: cannot find rappture2.h and librappture2.a, try using --with-rappture" >&5
+echo "$as_me: error: cannot find rappture2.h and librappture2.a, try using --with-rappture" >&2;}
+   { (exit 1); exit 1; }; }
+                fi
             else
                 echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-                { { echo "$as_me:$LINENO: error: cannot find rappture2.h and librappture2.a, try using --with-rappture" >&5
-echo "$as_me: error: cannot find rappture2.h and librappture2.a, try using --with-rappture" >&2;}
-   { (exit 1); exit 1; }; }
-            fi
-        else
-            echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-            { { echo "$as_me:$LINENO: error: cannot find rappture2.h and librappture2.a inside $with_rappture, try using --with-rappture" >&5
+                { { echo "$as_me:$LINENO: error: cannot find rappture2.h and librappture2.a inside $with_rappture, try using --with-rappture" >&5
 echo "$as_me: error: cannot find rappture2.h and librappture2.a inside $with_rappture, try using --with-rappture" >&2;}
    { (exit 1); exit 1; }; }
+            fi
         fi
+    else
+        RP2_INCL_DIR="$prefix/include/rappture2"
+        RP_DIR="$prefix"
+        echo "$as_me:$LINENO: result: set to prefix" >&5
+echo "${ECHO_T}set to prefix" >&6
     fi
 else
 
