added alternative Rappture:result function to tcl bindings added Rappture::Units::convert function. adjusted makefile for more files to compile adjusted configure file to once again check for bltInt.h adjusted children function to allow for blank path

diff --git a/src/tcl/configure.in b/src/tcl/configure.in
--- a/src/tcl/configure.in
+++ b/src/tcl/configure.in
@@ -126,64 +126,64 @@ SC_LOAD_TCLCONFIG
 # Look for bltInt.h on the normal include path.  If not found, look
 # for it in the --with-blt directory.
 #--------------------------------------------------------------------
-#AC_MSG_CHECKING([for bltInt.h])
-#BLT_SRC_DIR=""
-#if test "x$blt_source_dir" != "x" ; then
-#  #
-#  # Verify that a tclConfig.sh file exists in the directory specified 
-#  # by --with-blt. 
-#  #
-#  if test -r "$blt_source_dir/bltInt.h" ; then
-#    BLT_SRC_DIR="$blt_source_dir"
-#  elif test -r "$blt_source_dir/src/bltInt.h" ; then
-#    BLT_SRC_DIR="$blt_source_dir/src"
-#  fi
-#else 
-#  #
-#  # Otherwise, search for the bltInt.h include file...
-#  # 1. Search previously named locations.
-#  # 
-#  for dir in \
-#   $prefix \
-#   $exec_prefix
-#  do
-#    if test -r "$dir/bltInt.h" ; then
-#      BLT_SRC_DIR="$dir"
-#      break
-#    elif test -r "$dir/include/bltInt.h" ; then
-#      BLT_SRC_DIR="$dir/lib"
-#      break
-#    fi
-#  done
-#  #
-#  #  2. Search source directories.
-#  # 
-#  if test "x$BLT_SRC_DIR" = "x" ; then
-#    for dir in \
-#     `ls -dr ../blt[[2-3]].[[0-9]]* 2>/dev/null` \
-#     ../blt \
-#     `ls -dr ../../blt[[2-3]].[[0-9]]* 2>/dev/null` \
-#     ../../blt \
-#     `ls -dr ../../../blt[[2-3]].[[0-9]]* 2>/dev/null` \
-#     ../../../blt 
-#    do
-#      if test -r "$dir/bltInt.h" ; then
-#	tclConfigFile="$dir/bltInt.h"
-#	break
-#      fi
-#    done
-#  fi
-#fi
-#
-#AC_MSG_RESULT([${BLT_SRC_DIR}])
-#
-#if test "x$BLT_SRC_DIR" = "x" ; then
-#  echo "can't find BLT include file \"bltInt.h\""
-#  echo "use --with-blt=DIR to specify the location of the BLT sources"
-#  exit 1
-#fi
-#
-#AC_SUBST(BLT_SRC_DIR)
+AC_MSG_CHECKING([for bltInt.h])
+BLT_SRC_DIR=""
+if test "x$blt_source_dir" != "x" ; then
+  #
+  # Verify that a tclConfig.sh file exists in the directory specified 
+  # by --with-blt. 
+  #
+  if test -r "$blt_source_dir/bltInt.h" ; then
+    BLT_SRC_DIR="$blt_source_dir"
+  elif test -r "$blt_source_dir/src/bltInt.h" ; then
+    BLT_SRC_DIR="$blt_source_dir/src"
+  fi
+else 
+  #
+  # Otherwise, search for the bltInt.h include file...
+  # 1. Search previously named locations.
+  # 
+  for dir in \
+   $prefix \
+   $exec_prefix
+  do
+    if test -r "$dir/bltInt.h" ; then
+      BLT_SRC_DIR="$dir"
+      break
+    elif test -r "$dir/include/bltInt.h" ; then
+      BLT_SRC_DIR="$dir/lib"
+      break
+    fi
+  done
+  #
+  #  2. Search source directories.
+  # 
+  if test "x$BLT_SRC_DIR" = "x" ; then
+    for dir in \
+     `ls -dr ../blt[[2-3]].[[0-9]]* 2>/dev/null` \
+     ../blt \
+     `ls -dr ../../blt[[2-3]].[[0-9]]* 2>/dev/null` \
+     ../../blt \
+     `ls -dr ../../../blt[[2-3]].[[0-9]]* 2>/dev/null` \
+     ../../../blt 
+    do
+      if test -r "$dir/bltInt.h" ; then
+	tclConfigFile="$dir/bltInt.h"
+	break
+      fi
+    done
+  fi
+fi
+
+AC_MSG_RESULT([${BLT_SRC_DIR}])
+
+if test "x$BLT_SRC_DIR" = "x" ; then
+  echo "can't find BLT include file \"bltInt.h\""
+  echo "use --with-blt=DIR to specify the location of the BLT sources"
+  exit 1
+fi
+
+AC_SUBST(BLT_SRC_DIR)
 
 #--------------------------------------------------------------------
 # __CHANGE__
